server:
  port: 8088
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  application:
    name: stocks-observer
  r2dbc:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 4
      max-size: 16
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_NUMBERS_FOR_ENUMS: true
      FAIL_ON_NULL_FOR_PRIMITIVES: true
      USE_BIG_DECIMAL_FOR_FLOATS: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084
#          jwk-set-uri:

application:
  client:
    sourceUrl: http://localhost:8086/api/v1/sec
    apikey: 31f45a0d-cdf6-44bb-b205-efd7484c0716

logging:
  level:
    ROOT: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{36}){magenta} - %msg%n"
