@startuml
skinparam sequenceArrowThickneSFC 2
skinparam roundcorner 20

database PostgreSQL as DB order 80

box "External"
participant StocksFeedService as SFC
end box

box "Stocks Observer Application"
participant StocksClient as SC
participant StocksService as SS
participant StocksHistoryRepository as SHR
end box

SC --> SFC: getCompanies
activate SFC
SC <-- SFC: CompaniesList
SC --> SS: storeInTempStorage
deactivate SFC

SC --> SFC: getStocksForCompany(sheduled)
activate SFC
SC <-- SFC: getCompanyCurrentStock
SC --> SS: storeInQueue
deactivate SFC

activate SS
SS --> SS: calculateDiff
SS --> SHR: saveStocksFromQueueToHistory
SHR --> DB: saveStocksFromQueueToHistory
deactivate SS

SS --> SS: printTop5
activate SS
SS --> SHR: getTop5
SHR --> DB: getTop5
SHR <-- DB: top5
SS <-- SHR: top5
deactivate SS

@enduml